package com.example.octoevents.web.controller.util

import com.example.octoevents.domain.issue.*

//fun loadIssueEvent(): IssuesEvent {
//    return IssuesEvent(
//        1,
//        "refs/heads/master",
//        "23b52ae89a9a7fcbc74dedcf3699bcd479950e3b",
//        "eed16eb6b3fa068903bd661847805b43f30449b3",
//        Repository(
//            285380782,
//            "MDEwOlJlcG9zaXRvcnkyODUzODA3ODI=",
//            "config-files",
//            "thiagoporb/config-files",
//            false,
//            Owner(
//                605679,
//                "thiagoporb",
//                "thiagoporb@hotmail.com",
//                "thiagoporb",
//                "MDQ6VXNlcjYwNTY3OQ==",
//                "https://avatars3.githubusercontent.com/u/605679?v=4",
//                "",
//                "https://api.github.com/users/thiagoporb",
//                "https://github.com/thiagoporb",
//                "https://api.github.com/users/thiagoporb/followers",
//                "https://api.github.com/users/thiagoporb/following{/other_user}",
//                "https://api.github.com/users/thiagoporb/gists{/gist_id}",
//                "https://api.github.com/users/thiagoporb/starred{/owner}{/repo}",
//                "https://api.github.com/users/thiagoporb/subscriptions",
//                "https://api.github.com/users/thiagoporb/orgs",
//                "https://api.github.com/users/thiagoporb/repos",
//                "https://api.github.com/users/thiagoporb/events{/privacy}",
//                "https://api.github.com/users/thiagoporb/received_events",
//                "User",
//                false
//            ),
//            "https://github.com/thiagoporb/config-files",
//            "arquivos de configurações para microserviços",
//            false,
//            "https://github.com/thiagoporb/config-files",
//            "https://api.github.com/repos/thiagoporb/config-files/forks",
//            "https://api.github.com/repos/thiagoporb/config-files/keys{/key_id}",
//            "https://api.github.com/repos/thiagoporb/config-files/collaborators{/collaborator}",
//            "https://api.github.com/repos/thiagoporb/config-files/teams",
//            "https://api.github.com/repos/thiagoporb/config-files/hooks",
//            "https://api.github.com/repos/thiagoporb/config-files/issues/events{/number}",
//            "https://api.github.com/repos/thiagoporb/config-files/events",
//            "https://api.github.com/repos/thiagoporb/config-files/assignees{/user}",
//            "https://api.github.com/repos/thiagoporb/config-files/branches{/branch}",
//            "https://api.github.com/repos/thiagoporb/config-files/tags",
//            "https://api.github.com/repos/thiagoporb/config-files/git/blobs{/sha}",
//            "https://api.github.com/repos/thiagoporb/config-files/git/tags{/sha}",
//            "https://api.github.com/repos/thiagoporb/config-files/git/refs{/sha}",
//            "https://api.github.com/repos/thiagoporb/config-files/git/trees{/sha}",
//            "https://api.github.com/repos/thiagoporb/config-files/statuses/{sha}",
//            "https://api.github.com/repos/thiagoporb/config-files/languages",
//            "https://api.github.com/repos/thiagoporb/config-files/stargazers",
//            "https://api.github.com/repos/thiagoporb/config-files/contributors",
//            "https://api.github.com/repos/thiagoporb/config-files/subscribers",
//            "https://api.github.com/repos/thiagoporb/config-files/subscription",
//            "https://api.github.com/repos/thiagoporb/config-files/commits{/sha}",
//            "https://api.github.com/repos/thiagoporb/config-files/git/commits{/sha}",
//            "https://api.github.com/repos/thiagoporb/config-files/comments{/number}",
//            "https://api.github.com/repos/thiagoporb/config-files/issues/comments{/number}",
//            "https://api.github.com/repos/thiagoporb/config-files/contents/{+path}",
//            "https://api.github.com/repos/thiagoporb/config-files/compare/{base}...{head}",
//            "https://api.github.com/repos/thiagoporb/config-files/merges",
//            "https://api.github.com/repos/thiagoporb/config-files/{archive_format}{/ref}",
//            "https://api.github.com/repos/thiagoporb/config-files/downloads",
//            "https://api.github.com/repos/thiagoporb/config-files/issues{/number}",
//            "https://api.github.com/repos/thiagoporb/config-files/pulls{/number}",
//            "https://api.github.com/repos/thiagoporb/config-files/milestones{/number}",
//            "https://api.github.com/repos/thiagoporb/config-files/notifications{?since,all,participating}",
//            "https://api.github.com/repos/thiagoporb/config-files/labels{/name}",
//            "https://api.github.com/repos/thiagoporb/config-files/releases{/id}",
//            "https://api.github.com/repos/thiagoporb/config-files/deployments",
//            1596654428,
//            "2020-08-19T22:56:03Z",
//            1597882390,
//            "git://github.com/thiagoporb/config-files.git",
//            "git@github.com:thiagoporb/config-files.git",
//            "https://github.com/thiagoporb/config-files.git",
//            "https://github.com/thiagoporb/config-files",
//            null,
//            44,
//            0,
//            0,
//            null,
//            true,
//            true,
//            true,
//            true,
//            false,
//            0,
//            null,
//            false,
//            false,
//            0,
//            License(
//                "apache-2.0",
//                "Apache License 2.0",
//                "Apache-2.0",
//                "https://api.github.com/licenses/apache-2.0",
//                "MDc6TGljZW5zZTI="
//            ),
//            0,
//            0,
//            0,
//            "master",
//            0,
//            "master"
//        ),
//        Pusher(
//            "thiagoporb",
//            "thiagoporb@hotmail.com"
//        ),
//        Sender(
//            605679,
//            "thiagoporb",
//            "MDQ6VXNlcjYwNTY3OQ==",
//            "https://avatars3.githubusercontent.com/u/605679?v=4",
//            "",
//            "https://api.github.com/users/thiagoporb",
//            "https://github.com/thiagoporb",
//            "https://api.github.com/users/thiagoporb/followers",
//            "https://api.github.com/users/thiagoporb/following{/other_user}",
//            "https://api.github.com/users/thiagoporb/gists{/gist_id}",
//            "https://api.github.com/users/thiagoporb/starred{/owner}{/repo}",
//            "https://api.github.com/users/thiagoporb/subscriptions",
//            "https://api.github.com/users/thiagoporb/orgs",
//            "https://api.github.com/users/thiagoporb/repos",
//            "https://api.github.com/users/thiagoporb/events{/privacy}",
//            "https://api.github.com/users/thiagoporb/received_events",
//            "User",
//            false
//        ),
//        false,
//        false,
//        false,
//        null,
//        "https://github.com/thiagoporb/config-files/compare/23b52ae89a9a...eed16eb6b3fa",
//        mutableListOf(
//            Commit(
//                "eed16eb6b3fa068903bd661847805b43f30449b3",
//                "5a1de85beba044bd9f828bc1e18188612a88a2f6",
//                true,
//                "Update api-gateway.yaml",
//                "2020-08-19T21:13:09-03:00",
//                "https://github.com/thiagoporb/config-files/commit/eed16eb6b3fa068903bd661847805b43f30449b3",
//                Author(
//                    "Thiago",
//                    "thiagoporb@hotmail.com",
//                    "thiagoporb"
//                ),
//                Committer(
//                    "GitHub",
//                    "noreply@github.com",
//                    "web-flow"
//                ),
//                mutableListOf(),
//                mutableListOf(),
//                mutableListOf("api-gateway.yaml")
//
//            )
//        ),
//        HeadCommit(
//            "eed16eb6b3fa068903bd661847805b43f30449b3",
//            "5a1de85beba044bd9f828bc1e18188612a88a2f6",
//            true,
//            "Update api-gateway.yaml",
//            "2020-08-19T21:13:09-03:00",
//            "https://github.com/thiagoporb/config-files/commit/eed16eb6b3fa068903bd661847805b43f30449b3",
//            Author(
//                "Thiago",
//                "thiagoporb@hotmail.com",
//                "thiagoporb"
//            ),
//            Committer(
//                "GitHub",
//                "noreply@github.com",
//                "web-flow"
//            ),
//            mutableListOf(),
//            mutableListOf(),
//            mutableListOf("api-gateway.yaml")
//
//        )
//    )
//}


fun loadIssueEvent(): IssueEvent {
    return IssueEvent(
        id = 1,
        action = "edited",
        issue = getIssue(),
        changes = Change(),
        repository = getRepository(),
        sender = getSender()
    )
}

private fun getIssue(): Issue {
    return Issue(
        url = "https://api.github.com/repos/Codertocat/Hello-World/issues/1",
        repositoryUrl = "https://api.github.com/repos/Codertocat/Hello-World",
        labelsUrl = "https://api.github.com/repos/Codertocat/Hello-World/issues/1/labels{/name}",
        commentsUrl = "https://api.github.com/repos/Codertocat/Hello-World/issues/1/comments",
        eventsUrl = "https://api.github.com/repos/Codertocat/Hello-World/issues/1/events",
        htmlUrl = "https://github.com/Codertocat/Hello-World/issues/1",
        id = 444500041,
        nodeId = "MDU6SXNzdWU0NDQ1MDAwNDE=",
        number = 1,
        title = "Spelling error in the README file",
        user = User(
            login = "Codertocat",
            id = 21031067,
            nodeId = "MDQ6VXNlcjIxMDMxMDY3",
            avatarUrl = "https://avatars1.githubusercontent.com/u/21031067?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/Codertocat",
            htmlUrl = "https://github.com/Codertocat",
            followersUrl = "https://api.github.com/users/Codertocat/followers",
            followingUrl = "https://api.github.com/users/Codertocat/following{/other_user}",
            gistsUrl = "https://api.github.com/users/Codertocat/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/Codertocat/subscriptions",
            organizationsUrl = "https://api.github.com/users/Codertocat/orgs",
            reposUrl = "https://api.github.com/users/Codertocat/repos",
            eventsUrl = "https://api.github.com/users/Codertocat/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/Codertocat/received_events",
            type = "User",
            siteAdmin = false
        ),
        labels = mutableListOf(
            Label(
                id = 1362934389,
                nodeId = "MDU6TGFiZWwxMzYyOTM0Mzg5",
                url = "https://api.github.com/repos/Codertocat/Hello-World/labels/bug",
                name = "bug",
                color = "d73a4a",
                _default = true
            )
        ),
        state = "open",
        locked = false,
        assignee = Assignee(
            login = "Codertocat",
            id = 21031067,
            nodeId = "MDQ6VXNlcjIxMDMxMDY3",
            avatarUrl = "https://avatars1.githubusercontent.com/u/21031067?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/Codertocat",
            htmlUrl = "https://github.com/Codertocat",
            followersUrl = "https://api.github.com/users/Codertocat/followers",
            followingUrl = "https://api.github.com/users/Codertocat/following{/other_user}",
            gistsUrl = "https://api.github.com/users/Codertocat/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/Codertocat/subscriptions",
            organizationsUrl = "https://api.github.com/users/Codertocat/orgs",
            reposUrl = "https://api.github.com/users/Codertocat/repos",
            eventsUrl = "https://api.github.com/users/Codertocat/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/Codertocat/received_events",
            type = "User",
            siteAdmin = false
        ),
        assignees = mutableListOf(
            Assignee(
                login = "Codertocat",
                id = 21031067,
                nodeId = "MDQ6VXNlcjIxMDMxMDY3",
                avatarUrl = "https://avatars1.githubusercontent.com/u/21031067?v=4",
                gravatarId = "",
                url = "https://api.github.com/users/Codertocat",
                htmlUrl = "https://github.com/Codertocat",
                followersUrl = "https://api.github.com/users/Codertocat/followers",
                followingUrl = "https://api.github.com/users/Codertocat/following{/other_user}",
                gistsUrl = "https://api.github.com/users/Codertocat/gists{/gist_id}",
                starredUrl = "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
                subscriptionsUrl = "https://api.github.com/users/Codertocat/subscriptions",
                organizationsUrl = "https://api.github.com/users/Codertocat/orgs",
                reposUrl = "https://api.github.com/users/Codertocat/repos",
                eventsUrl = "https://api.github.com/users/Codertocat/events{/privacy}",
                receivedEventsUrl = "https://api.github.com/users/Codertocat/received_events",
                type = "User",
                siteAdmin = false
            )
        ),
        milestone = Milestone(
            url = "https://api.github.com/repos/Codertocat/Hello-World/milestones/1",
            htmlUrl = "https://github.com/Codertocat/Hello-World/milestone/1",
            labelsUrl = "https://api.github.com/repos/Codertocat/Hello-World/milestones/1/labels",
            id = 4317517,
            nodeId = "MDk6TWlsZXN0b25lNDMxNzUxNw==",
            number = 1,
            title = "v1.0",
            description = "Add new space flight simulator",
            creator = Creator(
                login = "Codertocat",
                id = 21031067,
                nodeId = "MDQ6VXNlcjIxMDMxMDY3",
                avatarUrl = "https://avatars1.githubusercontent.com/u/21031067?v=4",
                gravatarId = "",
                url = "https://api.github.com/users/Codertocat",
                htmlUrl = "https://github.com/Codertocat",
                followersUrl = "https://api.github.com/users/Codertocat/followers",
                followingUrl = "https://api.github.com/users/Codertocat/following{/other_user}",
                gistsUrl = "https://api.github.com/users/Codertocat/gists{/gist_id}",
                starredUrl = "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
                subscriptionsUrl = "https://api.github.com/users/Codertocat/subscriptions",
                organizationsUrl = "https://api.github.com/users/Codertocat/orgs",
                reposUrl = "https://api.github.com/users/Codertocat/repos",
                eventsUrl = "https://api.github.com/users/Codertocat/events{/privacy}",
                receivedEventsUrl = "https://api.github.com/users/Codertocat/received_events",
                type = "User",
                siteAdmin = false
            ),
            openIssues = 1,
            closedIssues = 0,
            state = "closed",
            createdAt = "2019-05-15T15:20:17Z",
            updatedAt = "2019-05-15T15:20:18Z",
            dueOn = "2019-05-23T07:00:00Z",
            closedAt = "2019-05-15T15:20:18Z"
        ),
        comments = 0,
        createdAt = "2019-05-15T15:20:18Z",
        updatedAt = "2019-05-15T15:20:18Z",
        closedAt = null,
        authorAssociation = "OWNER",
        body = "It looks like you accidently spelled 'commit' with two 't's."
    )
}

private fun getRepository(): Repository {
    return Repository(
        id = 186853002,
        nodeId = "MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=",
        name = "Hello-World",
        fullName = "Codertocat/Hello-World",
        _private = false,
        owner = Owner(
            login = "Codertocat",
            id = 21031067,
            nodeId = "MDQ6VXNlcjIxMDMxMDY3",
            avatarUrl = "https://avatars1.githubusercontent.com/u/21031067?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/Codertocat",
            htmlUrl = "https://github.com/Codertocat",
            followersUrl = "https://api.github.com/users/Codertocat/followers",
            followingUrl = "https://api.github.com/users/Codertocat/following{/other_user}",
            gistsUrl = "https://api.github.com/users/Codertocat/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/Codertocat/subscriptions",
            organizationsUrl = "https://api.github.com/users/Codertocat/orgs",
            reposUrl = "https://api.github.com/users/Codertocat/repos",
            eventsUrl = "https://api.github.com/users/Codertocat/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/Codertocat/received_events",
            type = "User",
            siteAdmin = false
        ),
        htmlUrl = "https://github.com/Codertocat/Hello-World",
        description = null,
        fork = false,
        url = "https://api.github.com/repos/Codertocat/Hello-World",
        forksUrl = "https://api.github.com/repos/Codertocat/Hello-World/forks",
        keysUrl = "https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}",
        collaboratorsUrl = "https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}",
        teamsUrl = "https://api.github.com/repos/Codertocat/Hello-World/teams",
        hooksUrl = "https://api.github.com/repos/Codertocat/Hello-World/hooks",
        issueEventsUrl = "https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}",
        eventsUrl = "https://api.github.com/repos/Codertocat/Hello-World/events",
        assigneesUrl = "https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}",
        branchesUrl = "https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}",
        tagsUrl = "https://api.github.com/repos/Codertocat/Hello-World/tags",
        blobsUrl = "https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}",
        gitTagsUrl = "https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}",
        gitRefsUrl = "https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}",
        treesUrl = "https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}",
        statusesUrl = "https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}",
        languagesUrl = "https://api.github.com/repos/Codertocat/Hello-World/languages",
        stargazersUrl = "https://api.github.com/repos/Codertocat/Hello-World/stargazers",
        contributorsUrl = "https://api.github.com/repos/Codertocat/Hello-World/contributors",
        subscribersUrl = "https://api.github.com/repos/Codertocat/Hello-World/subscribers",
        subscriptionUrl = "https://api.github.com/repos/Codertocat/Hello-World/subscription",
        commitsUrl = "https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}",
        gitCommitsUrl = "https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}",
        commentsUrl = "https://api.github.com/repos/Codertocat/Hello-World/comments{/number}",
        issueCommentUrl = "https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}",
        contentsUrl = "https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}",
        compareUrl = "https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}",
        mergesUrl = "https://api.github.com/repos/Codertocat/Hello-World/merges",
        archiveUrl = "https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}",
        downloadsUrl = "https://api.github.com/repos/Codertocat/Hello-World/downloads",
        issuesUrl = "https://api.github.com/repos/Codertocat/Hello-World/issues{/number}",
        pullsUrl = "https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}",
        milestonesUrl = "https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}",
        notificationsUrl = "https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}",
        labelsUrl = "https://api.github.com/repos/Codertocat/Hello-World/labels{/name}",
        releasesUrl = "https://api.github.com/repos/Codertocat/Hello-World/releases{/id}",
        deploymentsUrl = "https://api.github.com/repos/Codertocat/Hello-World/deployments",
        createdAt = "2019-05-15T15:19:25Z",
        updatedAt = "2019-05-15T15:19:27Z",
        pushedAt = "2019-05-15T15:20:13Z",
        gitUrl = "git://github.com/Codertocat/Hello-World.git",
        sshUrl = "git@github.com:Codertocat/Hello-World.git",
        cloneUrl = "https://github.com/Codertocat/Hello-World.git",
        svnUrl = "https://github.com/Codertocat/Hello-World",
        homepage = null,
        size = 0,
        stargazersCount = 0,
        watchersCount = 0,
        language = null,
        hasIssues = true,
        hasProjects = true,
        hasDownloads = true,
        hasWiki = true,
        hasPages = true,
        forksCount = 0,
        mirrorUrl = null,
        archived = false,
        disabled = false,
        openIssuesCount = 1,
        license = null,
        forks = 0,
        openIssues = 1,
        watchers = 0,
        defaultBranch = "master"
    )
}

private fun getSender(): Sender {
    return Sender(
        login = "Codertocat",
        id = 21031067,
        nodeId = "MDQ6VXNlcjIxMDMxMDY3",
        avatarUrl = "https://avatars1.githubusercontent.com/u/21031067?v=4",
        gravatarId = "",
        url = "https://api.github.com/users/Codertocat",
        htmlUrl = "https://github.com/Codertocat",
        followersUrl = "https://api.github.com/users/Codertocat/followers",
        followingUrl = "https://api.github.com/users/Codertocat/following{/other_user}",
        gistsUrl = "https://api.github.com/users/Codertocat/gists{/gist_id}",
        starredUrl = "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
        subscriptionsUrl = "https://api.github.com/users/Codertocat/subscriptions",
        organizationsUrl = "https://api.github.com/users/Codertocat/orgs",
        reposUrl = "https://api.github.com/users/Codertocat/repos",
        eventsUrl = "https://api.github.com/users/Codertocat/events{/privacy}",
        receivedEventsUrl = "https://api.github.com/users/Codertocat/received_events",
        type = "User",
        siteAdmin = false
    )
}